[package]
name = "cshop-io"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cshop-core = { workspace = true }
image = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
miniz_oxide = { workspace = true }
gif = { workspace = true }
png = { workspace = true }
moxcms = { workspace = true }
bytemuck = { workspace = true }
zune-jpeg = { workspace = true }
zune-core = { workspace = true }
tiff = { workspace = true }

[dev-dependencies]
gif = { workspace = true }
