[package]
name = "cshop-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
moxcms = { workspace = true }
bytemuck = { workspace = true }
rayon = { workspace = true }
log = { workspace = true }
ahash = { workspace = true }
ab_glyph = { workspace = true }
ttf-parser = { workspace = true }

[dev-dependencies]
image = { workspace = true }
